services:
  - type: web
    name: artify-nst-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
